Repository ITCEN-group4/alssong-dalssong-kkakssong, pull requests merged in 2025-05, with the labels that each got.

#2 Chore: 프로젝트 이슈/PR 템플릿 구성
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/task.md
  .github/ISSUE_TEMPLATE/troubleshooting_report.md
  .github/pull_request_template.md
  .idea/.gitignore
  .idea/alsong-dalsong-cocktail.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: 설정세팅

#4 Feature/setting
  back/.gitattributes
  back/.gitignore
  back/build.gradle
  back/gradle/wrapper/gradle-wrapper.jar
  back/gradle/wrapper/gradle-wrapper.properties
  back/gradlew
  back/gradlew.bat
  back/settings.gradle
  back/src/main/java/com/group4/aldalka/AldalkaApplication.java
  back/src/main/java/com/group4/aldalka/global/error/ErrorCode.java
  back/src/main/java/com/group4/aldalka/global/error/ErrorResponse.java
  back/src/main/java/com/group4/aldalka/global/error/exception/BusinessException.java
  back/src/main/java/com/group4/aldalka/global/error/exception/GlobalExceptionHandler.java
  back/src/main/java/com/group4/aldalka/global/result/ResultCode.java
  back/src/main/java/com/group4/aldalka/global/result/ResultResponse.java
  back/src/main/resources/application.yml
  back/src/test/java/com/group4/aldalka/AldalkaApplicationTests.java
Labels: 설정세팅, 백엔드

#23 #12 feat: post entity make
  .idea/.gitignore
  .idea/alsong-dalsong-cocktail.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  back/src/main/java/com/group4/aldalka/domain/post/controller/PostController.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/PostRepository.java
  back/src/main/java/com/group4/aldalka/domain/post/service/BaseLiquor.java
  back/src/main/java/com/group4/aldalka/domain/post/service/Ingredient.java
  back/src/main/java/com/group4/aldalka/domain/post/service/Post.java
  back/src/main/java/com/group4/aldalka/domain/post/service/PostBaseLiquor.java
  back/src/main/java/com/group4/aldalka/domain/post/service/PostIngredient.java
  back/src/main/java/com/group4/aldalka/domain/post/service/UserLike.java
  back/src/main/java/com/group4/aldalka/domain/user/User.java
Labels: 백엔드
