Repository ITCEN-group4/alssong-dalssong-kkakssong, pull requests merged in 2025-06, with the labels that each got.

#34 feat: 칵테일 공식레시피 전체조회 기능 구현
  back/src/main/java/com/group4/aldalka/domain/post/controller/PostController.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/PagedPostResponse.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/PostResponse.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/PostSearchRequest.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/PostSearchResult.java
  back/src/main/java/com/group4/aldalka/domain/post/entity/BaseLiquor.java
  back/src/main/java/com/group4/aldalka/domain/post/entity/Ingredient.java
  back/src/main/java/com/group4/aldalka/domain/post/entity/Post.java
  back/src/main/java/com/group4/aldalka/domain/post/entity/PostBaseLiquor.java
  back/src/main/java/com/group4/aldalka/domain/post/entity/PostIngredient.java
  back/src/main/java/com/group4/aldalka/domain/post/entity/UserLike.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/PostRepository.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/PostRepositoryCustom.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/PostRepositoryImpl.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/UserLikeRepository.java
  back/src/main/java/com/group4/aldalka/domain/post/service/PostService.java
  back/src/main/java/com/group4/aldalka/domain/user/User.java
  back/src/main/java/com/group4/aldalka/global/config/QuerydslConfig.java
  back/src/main/java/com/group4/aldalka/global/result/ResultCode.java
  back/src/main/java/com/group4/aldalka/global/security/LoginUserArgumentResolver.java
  back/src/main/resources/application.yml
  back/src/test/java/com/group4/aldalka/domain/user/config/TestQueryDslConfig.java
  back/src/test/java/com/group4/aldalka/domain/user/service/AuthServiceTest.java
  back/src/test/java/com/group4/aldalka/domain/user/service/UserServiceTest.java
Labels: 백엔드, 칵테일공식

#39 feat: 칵테일 공식레시피 상세조회 기능 구현
  back/src/main/java/com/group4/aldalka/domain/post/controller/PostController.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/OfficialPostDetailResponse.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/UserLikeRepository.java
  back/src/main/java/com/group4/aldalka/domain/post/service/PostService.java
  back/src/main/java/com/group4/aldalka/global/error/ErrorCode.java
  back/src/main/java/com/group4/aldalka/global/result/ResultCode.java
Labels: 백엔드, 칵테일공식

#45 feat: 마이페이지 게시글 조회 구현
  back/src/main/java/com/group4/aldalka/domain/post/controller/MypageController.java
  back/src/main/java/com/group4/aldalka/domain/post/controller/PostController.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/PostSearchCondition.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/request/MypagePostSearchRequest.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/request/PostSearchRequest.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/response/MypagePostResponse.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/response/OfficialPostDetailResponse.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/response/PagedResponse.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/response/PostResponse.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/PostRepositoryCustom.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/PostRepositoryImpl.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/UserLikeRepository.java
  back/src/main/java/com/group4/aldalka/domain/post/service/PostService.java
  back/src/main/java/com/group4/aldalka/global/result/ResultCode.java
Labels: 백엔드, 마이페이지

#38 feat: 게시글 CRUD 및 AWS S3를 활용한 이미지 저장 및 불러오기 구현
  back/build.gradle
  back/src/main/java/com/group4/aldalka/domain/post/controller/ImageController.java
  back/src/main/java/com/group4/aldalka/domain/post/controller/PostController.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/ImageUploadRecord.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/OfficialPostDetailResponse.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/PostBaseLiquorDTO.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/PostIngredientDTO.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/request/PostCreateRequestDTO.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/request/PostRequestDTO.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/response/PostResponse.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/response/PostResponseDTO.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/response/PostSelectResponseDTO.java
  back/src/main/java/com/group4/aldalka/domain/post/entity/BaseLiquor.java
  back/src/main/java/com/group4/aldalka/domain/post/entity/Ingredient.java
  back/src/main/java/com/group4/aldalka/domain/post/entity/Post.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/BaseLiquorRepository.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/IngredientRepository.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/PostBaseLiquorRepository.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/PostIngredientRepository.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/PostRepository.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/PostRepositoryCustom.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/PostRepositoryImpl.java
  back/src/main/java/com/group4/aldalka/domain/post/service/ImageService.java
  back/src/main/java/com/group4/aldalka/domain/post/service/PostService.java
  back/src/main/java/com/group4/aldalka/domain/user/controller/UserController.java
  back/src/main/java/com/group4/aldalka/global/config/AwsConfig.java
Labels: 백엔드

#53 [Fix] 칵테일 공식레시피 전체조회 로직 수정
  back/src/main/java/com/group4/aldalka/domain/post/controller/MypageController.java
  back/src/main/java/com/group4/aldalka/domain/post/controller/PostController.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/PostSearchCondition.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/request/MypagePostSearchRequest.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/request/PostSearchRequest.java
  back/src/main/java/com/group4/aldalka/domain/post/dto/response/PagedResponse.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/PostRepositoryImpl.java
  back/src/main/java/com/group4/aldalka/domain/post/service/PostLikeService.java
  back/src/main/java/com/group4/aldalka/domain/post/service/PostService.java
  back/src/main/java/com/group4/aldalka/domain/user/service/UserService.java
Labels: 백엔드, 칵테일공식

#60 feat: 공식게시글 전체조회/상세 조회 비회원 허용
  back/src/main/java/com/group4/aldalka/domain/post/service/PostService.java
Labels: 백엔드, 칵테일공식

#65 test: 게시글 검색 기능 테스트코드 작성
  back/src/main/java/com/group4/aldalka/domain/post/entity/Post.java
  back/src/main/java/com/group4/aldalka/domain/post/entity/PostBaseLiquor.java
  back/src/main/java/com/group4/aldalka/domain/post/entity/PostIngredient.java
  back/src/main/java/com/group4/aldalka/domain/post/repository/PostRepositoryImpl.java
  back/src/main/java/com/group4/aldalka/global/result/ResultResponse.java
  back/src/test/java/com/group4/aldalka/domain/post/controller/PostControllerTest.java
Labels: 백엔드, 테스트
